### ISSUE TITLE
Understanding Request Authentication for Installation

### ISSUE THREAD

**Issue by PierFio** [octokit/request.js#191]
Hello, 

using @octokit/request v5.4.5

I am requesting the github interface in order to obtain the list of private projects of an organization using the request library. I have the correct right set for the installation and got an installation token calling:
```javascript
await session.request(
            'POST /app/installations/:installation_id/access_tokens',
            {
                headers: {
                    authorization: `token ${ appToken }`,
                },
                installation_id: installationId,
                permissions: {
                    organization_projects: 'write',
                }
            },
        );
```
Everything seems to go well...
```
core_1  |   {
core_1  |     token: 'v1.b4b574f9ae835800ab6326a96525e034a8d697c3',
core_1  |     expires_at: '2020-07-14T13:45:57Z',
core_1  |     permissions: { organization_projects: 'write' },
core_1  |     repository_selection: 'selected'
core_1  |   },
```
but then calling
```javascript
await session.request(
            'GET /app/orgs/:org/projects',
            {
                headers: {
                    authorization: `token ${ installToken }`,
                },
                org,
            },
        );
```
I have the following error:
```
core_1  | InstallationAccess ERROR RequestError [HttpError]: Not Found
core_1  |     at /node/app/node_modules/@octokit/request/dist-node/index.js:66:23
core_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
core_1  |     at async getInstallationAuthentication (/node/app/node_modules/@octokit/auth-app/dist-node/index.js:148:7)
core_1  |     at async hook (/node/app/node_modules/@octokit/auth-app/dist-node/index.js:280:7)
[...]
core_1  |   status: 404,
core_1  |   headers: {
core_1  |     'access-control-allow-origin': '*',
core_1  |     'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
core_1  |     connection: 'close',
core_1  |     'content-encoding': 'gzip',
core_1  |     'content-security-policy': "default-src 'none'",
core_1  |     'content-type': 'application/json; charset=utf-8',
core_1  |     date: 'Tue, 14 Jul 2020 15:23:07 GMT',
core_1  |     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
core_1  |     server: 'GitHub.com',
core_1  |     status: '404 Not Found',
core_1  |     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
core_1  |     'transfer-encoding': 'chunked',
core_1  |     vary: 'Accept-Encoding, Accept, X-Requested-With',
core_1  |     'x-content-type-options': 'nosniff',
core_1  |     'x-frame-options': 'deny',
core_1  |     'x-github-media-type': 'github.inertia-preview; format=json, github.machine-man-preview; format=json',
core_1  |     'x-github-request-id': '93C2:5190:6DD240:EFF5EE:5F0DCDDB',
core_1  |     'x-xss-protection': '1; mode=block'
core_1  |   },
core_1  |   request: {
core_1  |     method: 'POST',
core_1  |     url: 'https://api.github.com/app/installations//access_tokens',
core_1  |     headers: {
core_1  |       accept: 'application/vnd.github.inertia-preview+json,application/vnd.github.machine-man-preview+json',
core_1  |       'user-agent': '[REDACTED] octokit-rest.js/18.0.0 octokit-core.js/3.1.0 Node.js/12.18.1 (Linux 5.3; x64)',
core_1  |       authorization: 'bearer [REDACTED]',
core_1  |       'content-type': 'application/json; charset=utf-8'
core_1  |     },
core_1  |     body: '{}',
core_1  |     request: { hook: [Function: bound bound register] }
core_1  |   },
core_1  |   documentation_url: 'https://developer.github.com/v3'
core_1  | }
```

My understanding is a default hook is triggered to obtain another installation authentication but has no information for the installation_id and therefore fails.
I do not understand this behavior. Am I missing something? Should I have configured a specific hook before being able to access the endpoint ? Thank you for your help @gr2m 

PS the session object is the result of:
```
new Octokit({
            authStrategy: createAppAuth,
            auth: {
                id: process.env.GITHUB_APP_ID,
                privateKey: pemKey,
            },
            userAgent: 'blabla',
            baseUrl: 'https://api.github.com',
            previews: ['inertia', 'machine-man'],
        });
```

**Comment by gr2m** [comment]
The 404 error is see is not coming from the `GET /app/orgs/:org/projects` request, but from `POST https://api.github.com/app/installations//access_tokens`. The `createAppAuth` strategy is sending the request to retrieve an installation token automatically for you, you don't need to do that manually.

What you need to do though is to set the `auth.installationId` option.

Try this

```js
new Octokit({
  authStrategy: createAppAuth,
  auth: {
    id: process.env.GITHUB_APP_ID,
    privateKey: pemKey,
    installationid
  },
  userAgent: "blabla",
  previews: ["inertia"],
});

await session.request("GET /app/orgs/:org/projects", {
  headers: {
    authorization: `token ${installToken}`,
  },
  org,
});
```

**Comment by PierFio** [comment]
Thanks a lot for the fast help and this whole framework. That way, it works. Surprisingly (I was looking at [that](https://github.com/octokit/core.js#defaults), this is not working though:

```javascript
const sessionMaker = Octokit.defaults({
     authStrategy: createAppAuth,
      auth: {
          id: process.env.GITHUB_APP_ID,
          privateKey: pemKey,
      },
      userAgent: 'blabla',
      baseUrl: 'https://api.github.com',
      previews: ['inertia', 'machine-man'],
});
```
followed by

```javascript
const session = new sessionMaker(options => {
                    return {
                        ...options,
                        auth: {
                            ...options.auth,
                            installationId: installation.value,
                            permissions: {
                                organization_projects: 'write',
                            }
                        },
                    }
                });
```

**Comment by gr2m** [comment]
you are passing a function to `sessionMaker`, try passing the options object instead


```js
const session = new sessionMaker({
  ...options,
  auth: {
    ...options.auth,
    installationId,
    permissions: {
      organization_projects: "write",
    },
  },
});
```

**Comment by PierFio** [comment]
Yes, thank you, you are right of course. But do not you think that defeats the purpose of the default options? I mean I have defined a defaultOptions object that I specialize when calling a specific new Octokit(). But certainly not a big deal anyway...

**Comment by gr2m** [comment]
You can create a constructor which has the app auth strategy and app ID + private key configured

```js
const OctokitWithAppAuth = Octokit.defaults({
  authStrategy: createAppAuth,
  auth: {
    id: process.env.GITHUB_APP_ID,
    privateKey: pemKey,
  },
});
```

Then use that custom constructor to initiate instances for an installation

```js
const octokit = new OctokitWithAppAuth({
  auth: {
    installationId
  },
});
```

**Comment by PierFio** [comment]
Neat and nice. Thank you Gregor.
