### ISSUE TITLE
Scopes with 0Auth app returning 404 on create new `repos.createForAuthenticatedUser`

### ISSUE THREAD

**Issue by ed42311** [octokit/request.js#214]
Hope I'm doing something silly here and it will be easy to spot

Here is the code:  https://github.com/ed42311/github-new-repo

Not sure if there is a better way to present this, might be a bit much to test run, if you clone, install and `yarn start`
Oh you'll need to create an OAuth app and put CLIENT_ID and CLIENT_SECRET in a `.env`
`localhost:8080` will have a link you can press on, it should allow OAuth authentication, then get an access token
and it does this, then I'd like to auth an `octokit` instance and be able to create a new repo.

I've tried this action with a personal access token and it works, but through the auth flow I'm obviously missing something.
Querying for the access token:
```
    const tokenResponse = await axios({
      method: 'post',
      url: `https://github.com/login/oauth/access_token?client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&code=${requestToken}&scope=user%20public_repo%20repo`,
      headers: {
        accept: 'application/json',
      },
    })
 const accessToken = tokenResponse.data.access_token
```
then 
```
    const octokit = new Octokit({ auth: accessToken })
    const response = await octokit.repos.createForAuthenticatedUser({
      name: 'hello_world',
    })
```
response errors out in the trycatch
```
RequestError [HttpError]: Not Found
    at /Users/contextcue/code/experiments/node-oauth-example/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/contextcue/code/experiments/node-oauth-example/dist/index.js:39:26 {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 24 Jul 2020 18:10:10 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': 'public_repo, repo',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': 'CEA1:2742:1C206:431AD:5F1B2402',
    'x-oauth-client-id': '093b90a514074765c4d8',
    'x-oauth-scopes': '',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4996',
    'x-ratelimit-reset': '1595617064',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/user/repos',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.0.2 octokit-core.js/3.1.1 Node.js/14.6.0 (darwin; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"name":"hello_world"}',
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://developer.github.com/v3/repos/#create'
}
```
noticed that scopes are blank, so maybe I need to format scopes differently?  I've seen both `scopes` and `scope` used and tried both but no dice.

**Comment by ed42311** [comment]
Reading through the closed issues I did find this:  https://github.com/octokit/request.js/issues/83#issuecomment-518414597 which is cool, doesn't solve the problem but does provide an auth route through octokit.

```typescript
    const authResponse = await octokit.request('POST https://github.com/login/oauth/access_token', {
      client_id: CLIENT_ID,
      client_secret: CLIENT_SECRET,
      code: requestToken,
      scope: 'repo',
      headers: {
        accept: 'application/json',
      },
    })
    console.log(authResponse)
```
scope still comes back blank though
```sh
...
  'x-frame-options': 'deny',
    'x-github-request-id': 'CF58:175B:2AB9C:4C57A:5F1B2780',
    'x-xss-protection': '1; mode=block'
  },
  data: {
    access_token: '1e93bd38003a376a7ce5aca1fe5ac4bec7377b52',
    token_type: 'bearer',
    scope: ''
  }
```

**Comment by gr2m** [comment]
I see you created your own OAuth Server implementation. Have you seen https://github.com/octokit/oauth-app.js? Could you see if it works with that? Setup should be fairly straight forward

**Comment by ed42311** [comment]
@gr2m https://glitch.com/edit/#!/join/e725934d-0f4c-4bf1-98be-e3bbea8539bf

seems like that should be good?

![Screen Shot 2020-07-24 at 1 52 18 PM](https://user-images.githubusercontent.com/14878694/88429971-e51e5880-cdb4-11ea-8c9a-b749fab0c1e2.png)

`curl -H "Authorization: token ACCESS_TOKEN" --data '{"name":"NEW_REPO_NAME"}' https://api.github.com/user/repos`

**Comment by gr2m** [comment]
Hmm not sure why the server returns a 404 for `GET /api/github/oauth/callback?code=fad108a1ec278a3fa579&state=tkbgzt6xnrr`, I'll have to investigate. A reload returns a different error though, so I something is working. I don't see the "token" event being triggered though, do you?

**Comment by ed42311** [comment]
![Screen Shot 2020-07-24 at 2 19 03 PM](https://user-images.githubusercontent.com/14878694/88432001-a12d5280-cdb8-11ea-8455-061458cd7868.png)

it does seem to get the token bu then dies on the redirect?

![Screen Shot 2020-07-24 at 2 19 41 PM](https://user-images.githubusercontent.com/14878694/88432047-b86c4000-cdb8-11ea-9160-8aa5f63a0c24.png)

maybe I have that formatted incorrectly

**Comment by ed42311** [comment]
if I throw a `trycatch` in there it hits the same error as before

```sh
...
    'x-oauth-scopes': '',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4998',
    'x-ratelimit-reset': '1595625798',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/user/repos',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-oauth-app.js/1.1.2 Node.js/12.0.0 (linux; ' +
        'x64) octokit-core.js/3.1.1 Node.js/12.0.0 (linux; ' +
        'x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"name":"hello_world"}',
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://developer.github.com/v3/repos/#create'
}
```

and scopes seems to be empty

interestingly enough it does pass on a token, so maybe I need to let that roll on, pass it to octokit somehow, wait for that to finish and then call post?

![Screen Shot 2020-07-24 at 2 26 50 PM](https://user-images.githubusercontent.com/14878694/88432583-b8207480-cdb9-11ea-91a3-aefb6bd73d29.png)

**Comment by gr2m** [comment]
I'll investigate this problem the next few days

**Comment by ed42311** [comment]
No rush.  Thanks for checking in.

**Comment by ed42311** [comment]
Heya @gr2m had a chance to poke around?  Seems like octokit is pretty boss I'd like to use it, but atm I'm thinking of looking for alternatives.  I need to do pretty much what `code-sandbox` does:  https://github.com/codesandbox/codesandbox-client

auth a user through an app, push some files to a new repo, would've just stolen their implementation, but got lost in the weeds and couldn't find it :crab:

**Comment by gr2m** [comment]
sorry I didn't get to it yet, it's been a very busy week so far, I can't make promises. I did not forget about you though, please have some more patience with me

**Comment by ed42311** [comment]
Ah, no need to apologize, ya good :1st_place_medal:  Only keeping the conversation rolling, I understand the busy.  Hit me up when you get a minute and thanks for the ping. :taco:

**Comment by gr2m** [comment]
I'm still busy with https://github.com/probot/probot/pull/1274, but I expect to finish this in the next week, after that I'll catch up with the open issues and PRs in @octokit

**Comment by gr2m** [comment]
@ed42311 I'm very sorry I've neglected this issue for so long, I finally got back to it. Funny enough, I tried to reproduce the problem with the Glitch App again but couldn't, I was able to login with GitHub without a problem now starting at https://cottony-wary-basement.glitch.me/

Now the app still does not work, but the reason is that the token does not have the required scopes. The token the app creates has no scopes at all. The error includes the response headers, which include `'x-oauth-scopes': '',` (meaning the current OAuth token has no scopes) and `'x-accepted-oauth-scopes': 'public_repo, repo'` (meaning that one of these scopes is required). 

But you passe `scope: ["repo"]` to the `new OAuthApp` constructor, so I'm pretty certain that's where the problem lies, I'll investigate further and keep you posted.

Thanks for your patience with me
