### ISSUE TITLE
TypeError: oldEndpoint.defaults is not a function

### ISSUE THREAD

**Issue by fullstackzach** [octokit/request.js#48]
After upgrading [semantic-release/github](https://github.com/semantic-release/github), our dry run of our npm build started to fail with this stack trace

npx semantic-release
[11:02:00 AM] [semantic-release] › ℹ  Running semantic-release version 15.13.12
[11:02:00 AM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: oldEndpoint.defaults is not a function
    at withDefaults (../node_modules/@octokit/request/lib/with-defaults.js:6:32)
    at Object.<anonymous> (../node_modules/@octokit/request/index.js:8:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (../node_modules/@octokit/rest/lib/constructor.js:3:18)
TypeError: oldEndpoint.defaults is not a function
    at withDefaults (../node_modules/@octokit/request/lib/with-defaults.js:6:32)
    at Object.<anonymous> (../node_modules/@octokit/request/index.js:8:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (../node_modules/@octokit/rest/lib/constructor.js:3:18)%

I think this may actually be an issue with octokit/request - so I decided to create an issue here. 

It looks like in `@octokit/request/lib/index.js` withDefaults is expecting oldEndpoint.defaults to exist, but upon inspecting the object myself, I noticed `defaults` is actually a level deeper - `oldEndpoint.endpoint.defaults`. By updating @octokit/request/index.js line 1 to add .endpoint at the end of the line, in my node-modules resolved the error. `const endpoint = require('@octokit/endpoint').endpoint`.. But this is not a good workaround when it comes to publishing the project in the CI

@octokit/request@3.0.1 and @octokit/endpoint@4.3.0 were installed as dependencies of [semantic-release/github](https://github.com/semantic-release/github).  If a different version should be used by semantic-release/github, I could open an issue there too.

**Comment by gr2m** [comment]
I think `@octokit/endpoint@4.3.0` might be the problem, there was a breaking change in that version, I unpublished it shortly after. Could you try to delete your lock file and `node_modules` and run install again, see if it works then? Sorry for the trouble 😞

**Comment by fullstackzach** [comment]
That did it @gr2m thanks!

A bit of confusion on my end too - our Org's internal npm registry had that v4.3.0 cached so even after removing package-lock.json and node-modules, my install was still pulling it in.
I was able to have our registry clear that version from it's cache, and I am all good now 👍

**Comment by gr2m** [comment]
> our Org's internal npm registry had that v4.3.0 cached so even after removing package-lock.json and node-modules, my install was still pulling it in.

Oh that’s good to know. Usually I’d do another patch release which would undo v4.3.0, but this time I realised the problem only a minute after 4.3.0 was published so I thought unpublish should be good enough. I didn’t know that deletions don’t propagate to local caches
